config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  
  resources :parents
  resources :enfants
  devise_for :users

  get 'dashboard' => 'pages#dashboard'
  get 'parent'    => 'parents#new'

end

app/models/enfant.rb
class Enfant < ActiveRecord::Base
  belongs_to :user
  def age
  	now = Time.now.utc.to_date
  	now.year - date_de_naissance.year - (date_de_naissance.to_date.change(:year => now.year) > now ? 1 : 0)
  end
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  belongs_to :user
  #geocoded_by :ip_address
  geocoded_by :adresse # ActiveRecord
  after_validation :geocode          # auto-fetch coordinates
  def age
  	now = Time.now.utc.to_date
  	now.year - date_de_naissance.year - (date_de_naissance.to_date.change(:year => now.year) > now ? 1 : 0)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :enfants
  has_many :parents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/enfants_controller.rb
class EnfantsController < ApplicationController
  before_action :set_enfant, only: [:show, :edit, :update, :destroy]

  # GET /enfants
  # GET /enfants.json
  def index
    @enfants = Enfant.all
  end

  # GET /enfants/1
  # GET /enfants/1.json
  def show
  end

  # GET /enfants/new
  def new
    @enfant = current_user.enfants.build(date_de_naissance: Time.zone.parse("01-01-2000").to_date)
  end

  # GET /enfants/1/edit
  def edit
  end

  # POST /enfants
  # POST /enfants.json
  def create
    @enfant = current_user.enfants.build(enfant_params)

    respond_to do |format|
      if @enfant.save
        format.html { redirect_to @enfant, notice: 'Enfant was successfully created.' }
        format.json { render :show, status: :created, location: @enfant }
      else
        format.html { render :new }
        format.json { render json: @enfant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enfants/1
  # PATCH/PUT /enfants/1.json
  def update
    respond_to do |format|
      if @enfant.update(enfant_params)
        format.html { redirect_to @enfant, notice: 'Enfant was successfully updated.' }
        format.json { render :show, status: :ok, location: @enfant }
      else
        format.html { render :edit }
        format.json { render json: @enfant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enfants/1
  # DELETE /enfants/1.json
  def destroy
    @enfant.destroy
    respond_to do |format|
      format.html { redirect_to enfants_url, notice: 'Enfant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enfant
      @enfant = Enfant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enfant_params
      params.require(:enfant).permit(:nom, :prenom, :date_de_naissance)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def dashboard
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

#  def age
#    now = Time.now.utc.to_date
#    now.year - date_de_naissance.year - (date_de_naissance.to_date.change(:year => now.year) > now ? 1 : 0)
#  end

  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.all
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
  end

  # GET /parents/new @enfant = current_user.enfants.build
  def new
    @parent = current_user.parents.build(date_de_naissance: Time.zone.parse("01-01-1960").to_date)
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = current_user.parents.build(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render :show, status: :created, location: @parent }
      else
        format.html { render :new }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url, notice: 'Parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:nom, :prenom, :adresse, :telephone, :date_de_naissance)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enfants_helper.rb
module EnfantsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/enfants/_form.html.erb
<%= form_for(@enfant) do |f| %>
  <% if @enfant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enfant.errors.count, "error") %> prohibited this enfant from being saved:</h2>

      <ul>
      <% @enfant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :prenom %><br>
    <%= f.text_field :prenom %>
  </div>
  <div class="field">
    <%= f.label :date_de_naissance %><br>
    <%= f.date_select :date_de_naissance, { start_year: Time.now.year-18, end_year: Time.now.year-3 } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enfants/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Enfants</h1>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Date de naissance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enfants.each do |enfant| %>
      <tr>
        <td><%= enfant.nom %></td>
        <td><%= enfant.prenom %></td>
        <td><%= enfant.date_de_naissance %></td>
        <td><%= link_to 'Show', enfant %></td>
        <td><%= link_to 'Edit', edit_enfant_path(enfant) %></td>
        <td><%= link_to 'Destroy', enfant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enfant', new_enfant_path %>

app/views/enfants/edit.html.erb
<h1>Editing Enfant</h1>

<%= render 'form' %>

<%= link_to 'Show', @enfant %> |
<%= link_to 'Back', enfants_path %>

app/views/enfants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Enfants</h1>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Date de naissance</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enfants.each do |enfant| %>
      <tr>
        <td><%= enfant.nom %></td>
        <td><%= enfant.prenom %></td>
        <td><%= enfant.date_de_naissance %></td>
        <td><%= enfant.age %> ans</td>
        <td><%= link_to 'Show', enfant %></td>
        <td><%= link_to 'Edit', edit_enfant_path(enfant) %></td>
        <td><%= link_to 'Destroy', enfant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enfant', new_enfant_path %>

app/views/enfants/new.html.erb
<h1>New Enfant</h1>

<%= render 'form' %>

<%= link_to 'Back', enfants_path %>

app/views/enfants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @enfant.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @enfant.prenom %>
</p>

<p>
  <strong>Date de naissance:</strong>
  <%= @enfant.date_de_naissance %>
</p>

<%= link_to 'Edit', edit_enfant_path(@enfant) %> |
<%= link_to 'Back', enfants_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" id="logo"><img alt="Bus" src="logo.png" /></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Accueil <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Mes informations", parents_path %></li>
          <li><%= link_to "Mes enfants", enfants_path %></li>
          <li><%= link_to "Modifier mon mot de passe", edit_user_registration_path %></li>
          <li><%= link_to "Se déconnecter", destroy_user_session_path, :method => :delete %></li>

        <% else %>
          <li><%= link_to "Créer un compte", new_user_registration_path %></li>
          <li><%= link_to 'Se connecter', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test4</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
  <body>

    <%= render "layouts/navbar" %>


<%= yield %>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>

</body>
</html>

app/views/pages/dashboard.html.erb
<h1>Mon espace personnel</h1>

app/views/pages/index.html.erb
<h1>Bienvenue sur la page d'accueil</h1>

app/views/parents/_form.html.erb
<%= form_for(@parent) do |f| %>
  <% if @parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% @parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :prenom %><br>
    <%= f.text_field :prenom %>
  </div>
  <div class="field">
    <%= f.label :adresse %><br>
    <%= f.text_field :adresse %>
    <br>

  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :date_de_naissance %><br>
    <%= f.date_select :date_de_naissance, { start_year: 1920, end_year: 2000 } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form' %>

<%= link_to "Montrer", @parent %> |
<%= link_to "Retour", parents_path %>

app/views/parents/index.html.erb
<h1 class="titre">Liste des parents</h1>

<div class="table-responsive">
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Date de naissance</th>
        <th>Age</th>
        <th>Adresse</th>
        <th>Téléphone</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @parents.each do |parent| %>
        <tr>
          <td><%= parent.nom %></td>
          <td><%= parent.prenom %></td>
          <td><%= parent.date_de_naissance %></td>
          <td><%= parent.age %> ans</td>
          <td><%= parent.adresse %></td>
          <td><%= parent.telephone %></td>
          <td><%= link_to "Montrer", parent %></td>
          <td><%= link_to "Modifier", edit_parent_path(parent) %></td>
          <td><%= link_to "Supprimer", parent, method: :delete, data: { confirm: 'Etes-vous sûr ?' } %></td>
          </tr>
        <% end %>
    </tbody>
  </table>
</div>

<br>

<%= button_to 'Nouveau Parent', new_parent_path, method: :get, class: "btn btn-primary" %>

app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render "form" %>

<%= link_to "Retour", parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>


<div class="table-responsive">
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Date de naissance</th>
        <th>Age</th>
        <th>Adresse</th>
        <th>Téléphone</th>

      </tr>
    </thead>

    <tbody>

        <tr>
          <td><%= @parent.nom %></td>
          <td><%= @parent.prenom %></td>
          <td><%= @parent.date_de_naissance %></td>
          <td><%= @parent.age %> ans</td>
          <td><%= @parent.adresse %></td>
          <td><%= @parent.telephone %></td>

    </tbody>
  </table>
<div class="maps">
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=900x600&sensor=true&zoom=16&markers=#{@parent.latitude}%2C#{@parent.longitude}" %>
</div>
<br>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>